# -*- coding: utf-8 -*-
"""Web_Scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FAkuAeLPuiXcu3fzGomZ4H1J0DFNMop_
"""

import requests

def get_example():

    url = 'https://www.pqstec.com/InvoiceApps/values/GetProductListAll'
    response = requests.get(url)

    if response.status_code == 200:
        print("GET request successful!")
        # Print response content
        print(response.json())
    else:
        print("Failed to retrieve data")

def main():
    """
    Main function to execute the examples.
    """
    print("Executing GET example...")
    get_example()

if __name__ == "__main__":
    main()
    pass

def post_example():
    url = 'https://www.pqstec.com/InvoiceApps/values/GetProductListAll'
    data ={
           'Id': 232905,
           'CategoryId': None,
           'CategoryName': 'CHINA IMPORT',
           'UnitName': 'PCS',
           'Name': 'SS SPOON HOLDER',
           'LocalName': '',
           'Code': '3002195',
           'ParentCode': None,
           'ProductBarcode': '3002195',
           'Description': '',
           'BrandName': '', 'SizeName': '',
           'ColorName': '',
           'ModelName': None,
           'VariantName': None,
           'OldPrice': 0.0,
           'Price': 1200.0,
           'CostPrice': 0.0,
           'WarehouseList': [],
           'stock': 0.0,
           'TotalPurchase': 6.0,
           'LastPurchaseDate': '3-Jan-25',
           'LastPurchaseSupplier': 'DELHI ALUMINIUM FACTORY LTD(FOREIGN)',
           'TotalSales': 0.0,
           'LastSalesDate': '',
           'LastSalesCustomer': ' - ',
           'ImagePath': None,
           'Type': 'simple',
           'Status': 'publish',
           'CommissionAmount': 0.0,
           'CommissionPer': 0.0,
           'PCTN': 0.0}
    response = requests.post(url, json=data)

    # Check if the request was successful
    if response.status_code == 201:
        print("POST request successful!")
        # Print response content
        print(response.json())
    else:
        print("Failed to post data")

def main_p():
    print("\nExecuting POST example...")
    post_example()

if __name__ == "__main__":
    main_p()
    pass

def post_example():
    """
    Demonstrates a simple POST request using the `requests` library.
    Sends JSON data to a public API and prints the response.
    """
    url = 'https://jsonplaceholder.typicode.com/posts'
    data = {
        'title': 'foo',
        'body': 'bar',
        'userId': 10
    }
    response = requests.post(url, json=data)

    # Check if the request was successful
    if response.status_code == 201:
        print("POST request successful!")
        # Print response content
        print(response.json())
    else:
        print("Failed to post data")

def get_example():
    """
    Demonstrates a simple GET request using the `requests` library.
    Fetches data from a public API and prints the JSON response.
    """
    url = 'https://jsonplaceholder.typicode.com/posts/100'
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        print("GET request successful!")
        # Print response content
        print(response.json())
    else:
        print("Failed to retrieve data")

def main():
    """
    Main function to execute the examples.
    """
    print("Executing GET example...")
    get_example()
    print("\nExecuting POST example...")
    post_example()

if __name__ == "__main__":
    main()
    pass

